#constables internationalized enums
SERVICES_CENTRAUX=المصالح المركزية
SERVICES_DECONCENTRES=المصالح غير الممركزة
ORGANISMES_SOUS_TUTELLE=الهيئات الخاضعة للوصاية
ORGANES_TERRITORIAUX=الهيئات الاقليمية
AUTRE_SERVICES_SOUS_TUTELLE=الهيئات الاخرى الخاضعة للوصاية
footer.text=تقرير الاولويات والتخطيط للسنة \n وزارة ${portefeuille}
section1.ausujetprotefeuille.title.text=بخصوص المحفظة
section1.leministere.title.text=الوزارة
section1.leministere.organigramme.title.text=الهيكل التنظيمي للوزارة
section1.lamission.title.text=المهمة
section1.cartographie.title.text=خريطة برامج المحفظة
section1.cartographie.table.headers.1=هيكلة البرامج
section1.cartographie.table.headers.2=الهيكل التنظيمي
section1.ficheportefeuille.title.text=بطاقة المحفظة (انظر الجدول ادناه)
section1.ficheportefeuille.gestionnaire.text=المسير المسؤول: الوزير %s

section1.ficheportefeuille.table.1.title=توزيع اعتمادات الدفع ورخص الالتزام حسب البرنامج (بألاف دج) - الجدول ”ب“
section1.ficheportefeuille.table.2.title=توزيع رخص الالتزام واعتمادات الدفع حسب البرنامج (بألاف  دج):
section1.ficheportefeuille.table.3.title=توزيع اعتمادات البرامج حسب نوع مركز المسؤولية (بألاف  دج):

section1.ficheportefeuille.table.4.title=نفقات المحفظة حسب البرنامج والعنوان - السنة %s (بألاف  دج):
section1.ficheportefeuille.table.4.header.title=البرنامج

section1.ficheportefeuille.table.5.title=نفقات المحفظة حسب العنوان ونوع مركز المسؤولية - السنة %s (بألاف  دج):

section1.ficheportefeuille.table.6.title=تطور النفقات حسب البرنامج (بألاف  دج):
section1.ficheportefeuille.table.6.header.title=البرنامج
section1.ficheportefeuille.table.6.headers.1=النفقات الفعلية السنة %s
section1.ficheportefeuille.table.6.headers.2=تقديرات النفقات السنة %s
section1.ficheportefeuille.table.6.headers.3=النفقات المتوقعة %s
section1.ficheportefeuille.table.6.headers.4=النفقات المتوقعة %s
section1.ficheportefeuille.table.6.headers.5=النفقات المتوقعة %s
section1.ficheportefeuille.table.6.total.title=مجموع النفقات

section1.ficheportefeuille.table.7.title=تطور المناصب المالية المفتوحة حسب نوع المصالح
section1.ficheportefeuille.table.7.header.title=المصالح
section1.ficheportefeuille.table.7.headers.1=%s
section1.ficheportefeuille.table.7.headers.2=%s
section1.ficheportefeuille.table.7.headers.3=%s
section1.ficheportefeuille.table.7.headers.4=%s
section1.ficheportefeuille.table.7.headers.5=%s
section1.ficheportefeuille.table.7.total.title=مجموع المنصاب

section2.planification.title.1.text=التخطيط المفصل للبرنامج %02d
section2.planification.title.2.text=تقديم البرنامج
section2.planification.title.3.text=البرنامج %d: %s
section2.planification.justification.title=مبررات النفقات المتوقعة للسنة %s
section2.ficheprogramme.title.1.text=بطاقة البرنامج:
section2.ficheprogramme.title.2.text=اسم البرنامج: %d %s
section2.ficheprogramme.title.3.text=المسير المسؤول : %s
section2.ficheprogramme.table.3.title=نفقات البرنامج %d حسب العنوان ونوع مركز المسؤوليةالسنة %d (بألاف دج)

section2.ficheprogramme.table.4.title=نفقات البرنامج %s حسب البرنامج الفرعي (بألاف دج)
section2.ficheprogramme.table.4.header.title=البرنامج

section2.ficheprogramme.table.5.title=تطور النفقات حسب البرنامج الفرعي (بألاف دج)
section2.ficheprogramme.table.5.header.title=البرنامج الفرعي
section2.ficheprogramme.table.5.headers.1=النفقات الفعلية السنة %s
section2.ficheprogramme.table.5.headers.2=تقديرات النفقات السنة %s
section2.ficheprogramme.table.5.headers.3=النفقات المتوقعة %s
section2.ficheprogramme.table.5.headers.4=النفقات المتوقعة %s
section2.ficheprogramme.table.5.headers.5=النفقات المتوقعة %s
section2.ficheprogramme.table.5.total.title=مجموع النفقات
#-------------المشاريع الرئيسية------
princip.projet=المشاريع الرئيسية للبرنامج %03d
princip.projet.en.cours.gpe.title=قائمة المشاريع الكبرى للدولة -الجارية (بألاف دج)
princip.projet.en.cours.gpe.header.title=المشاريع الكبرى للدولة - الجارية

princip.projet.en.cours.projet.title=قائمة المشاريع - الجارية (بألاف دج)
princip.projet.en.cours.projet.header.title=المشاريع الجارية

princip.projet.en.cours.header.ae.reevaluation=رخصة الالتزام (إعادة التقييم) %s
princip.projet.en.cours.header.cp.annee=اعتمادات الدفع المتوفعة %s
princip.projet.en.cours.header.cp.annee.1=اعتمادات الدفع المتوقعة %s
princip.projet.en.cours.header.cp.annee.2=اعتمادات الدفع المتوقعة %s ومايليها

princip.projet.nouveau.projet.gpe.title=قائمة المشاريع الجديدة الكبرى (بألاف دج)
princip.projet.nouveau.projet.gpe.header.title=المشاريع الكبرى للدولة

princip.projet.nouveau.projet.projet.title=قائمة المشاريع الجديدة (بألاف دج)
princip.projet.nouveau.projet.projet.header.title=المشاريع الجديدة

#shared headers nouveaux projet
princip.projet.nouveau.projet.header.ae=رخصة الالتزام %s
princip.projet.nouveau.projet.header.cp.annee=اعتمادات الدفع المتوقعة %s
princip.projet.nouveau.projet.header.cp.annee.1=اعتمادات الدفع المتوقعة %s
princip.projet.nouveau.projet.header.cp.annee.2=اعتمادات الدفع المتوقعة للسنة %s ومايليها
##--------------------الجداول التكميلية---------------
etat.complementaire.title=الجداول التكميلية
etat.complementaire.evolution.postes.salariale.table.title=تقديرات تطور المناصب المفتوحة وكتلة الاجور (بألاف دج)
#نفقات الهيئات الخاضعة للوصاية
etat.complementaire.evolution.depenses.pricipaux.ost.title=نفقات الهيئات الخاضعة الرئيسية الخاضعة للوصاية (بألاف دج)
etat.complementaire.evolution.depenses.pricipaux.ost.header.title=الهيئات الخاضعة الرئيسية الخاضعة للوصاية
etat.complementaire.evolution.depenses.pricipaux.ost.headers.1=النفقات الفعلية السنة %s
etat.complementaire.evolution.depenses.pricipaux.ost.headers.2=تقديرات النفقات السنة %s
etat.complementaire.evolution.depenses.pricipaux.ost.headers.3=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.pricipaux.ost.headers.4=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.pricipaux.ost.headers.5=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.pricipaux.ost.total.title=المجموع
#النفقات حسب نوع الهيئة الخاضعة للوصاية
etat.complementaire.evolution.depenses.type.ost.title=النفقات حسب نوع الهيئة الخاضعة للوصاية (بألاف دج)
etat.complementaire.evolution.depenses.type.ost.header.title=الهيئات الخاضعة للوصاية حسب نوعها
etat.complementaire.evolution.depenses.type.ost.headers.1=النفقات الفعلية السنة %s
etat.complementaire.evolution.depenses.type.ost.headers.2=تقديرات النفقات السنة %s
etat.complementaire.evolution.depenses.type.ost.headers.3=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.type.ost.headers.4=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.type.ost.headers.5=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.type.ost.total.title=المجموع
#النفقات حسب الاقليم
etat.complementaire.evolution.depenses.territoire.title=تطور النفقات حسب الاقليم (بألاف دح)
etat.complementaire.evolution.depenses.territoire.header.title=الاقليم
etat.complementaire.evolution.depenses.territoire.headers.1=النفقات الفعلية السنة %s
etat.complementaire.evolution.depenses.territoire.headers.2=تقديرات النفقات السنة %s
etat.complementaire.evolution.depenses.territoire.headers.3=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.territoire.headers.4=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.territoire.headers.5=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.territoire.total.title=مجموع النفقات
#النفقات حسب مصدر التمويل
etat.complementaire.evolution.depenses.source.financement.title=تقديرات تطور النفقات حسب مصدر التمويل (بألاف دج)
etat.complementaire.evolution.depenses.source.financement.header.title=نوع مصدر التمويل
etat.complementaire.evolution.depenses.source.financement.headers.1=النفقات الفعلية السنة %s
etat.complementaire.evolution.depenses.source.financement.headers.2=تقديرات النفقات السنة %s
etat.complementaire.evolution.depenses.source.financement.headers.3=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.source.financement.headers.4=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.source.financement.headers.5=النفقات المتوقعة %s
etat.complementaire.evolution.depenses.source.financement.total.title=مجموع النفقات
