#constables internationalized enums
SERVICES_CENTRAUX=المصالح المركزية
SERVICES_DECONCENTRES=المصالح غير الممركزة
ORGANISMES_SOUS_TUTELLE=الهيئات الخاضعة للوصاية
ORGANES_TERRITORIAUX=الهيئات الاقليمية
AUTRE_SERVICES_SOUS_TUTELLE=الهيئات الاخرى الخاضعة للوصاية
PROGRAMME=البرامج
SOUS_PROGRAMME=البرنامج الفرعي
#general static content
footer.text=تقرير الاولويات والتخطيط للسنة \n وزارة ${portefeuille}
default.total=المجموع

#section 1 specific styles

    #cartographie
section1.cartographie.table.style=TextBasedTableBase

    #fiche portefeuille
section1.ficheportefeuille.table.styles.1=NumberBasedTableBase
section1.ficheportefeuille.table.styles.2=NumberBasedTableBase2

#section 1 static content
section1.ausujetprotefeuille.title.text=بخصوص المحفظة
section1.leministere.title.text=الوزارة
section1.leministere.organigramme.title.text=الهيكل التنظيمي للوزارة
section1.lamission.title.text=المهمة
section1.cartographie.title.text=خريطة برامج المحفظة
section1.cartographie.table.headers.1=هيكلة البرامج
section1.cartographie.table.headers.2=الهيكل التنظيمي
section1.ficheportefeuille.title.text=بطاقة المحفظة (انظر الجدول ادناه)
section1.ficheportefeuille.gestionnaire.text=المسير المسؤول: الوزير ${gestionnaire}
section1.ficheportefeuille.table.1.title=توزيع اعتمادات الدفع ورخص الالتزام حسب البرنامج (بألاف دج) - الجدول ”ب“
section1.ficheportefeuille.table.2.title=توزيع رخص الالتزام واعتمادات الدفع حسب البرنامج (بألاف  دج):
section1.ficheportefeuille.table.3.title=توزيع اعتمادات البرامج حسب نوع مركز المسؤولية (بألاف  دج):
section1.ficheportefeuille.table.4.title=نفقات المحفظة حسب البرنامج والعنوان - السنة ${n} (بألاف  دج):
section1.ficheportefeuille.table.4.header.title=البرنامج
section1.ficheportefeuille.table.5.title=نفقات المحفظة حسب العنوان ونوع مركز المسؤولية - السنة ${n} (بألاف  دج):
section1.ficheportefeuille.table.6.title=تطور النفقات حسب البرنامج (بألاف  دج):
section1.ficheportefeuille.table.6.headers.0=البرنامج
section1.ficheportefeuille.table.6.headers.1=النفقات الفعلية السنة %s
section1.ficheportefeuille.table.6.headers.2=تقديرات النفقات السنة %s
section1.ficheportefeuille.table.6.headers.3=النفقات المتوقعة %s
section1.ficheportefeuille.table.6.headers.4=النفقات المتوقعة %s
section1.ficheportefeuille.table.6.headers.5=النفقات المتوقعة %s
section1.ficheportefeuille.table.6.total=مجموع النفقات
section1.ficheportefeuille.table.7.title=تطور المناصب المالية المفتوحة حسب نوع المصالح
section1.ficheportefeuille.table.7.headers.0=المصالح
section1.ficheportefeuille.table.7.headers.1=%s
section1.ficheportefeuille.table.7.headers.2=%s
section1.ficheportefeuille.table.7.headers.3=%s
section1.ficheportefeuille.table.7.headers.4=%s
section1.ficheportefeuille.table.7.headers.5=%s
section1.ficheportefeuille.table.7.total=مجموع المنصاب

section2.planification.title.1.text=التخطيط المفصل للبرنامج %02d
section2.planification.title.2.text=تقديم البرنامج
section2.planification.title.3.text=البرنامج %d: %s
section2.ficheprogramme.title.1.text=بطاقة البرنامج:
section2.ficheprogramme.title.2.text=اسم البرنامج: %d %s
section2.ficheprogramme.title.3.text=المسير المسؤول : %s