#constables internationalized enums
SERVICES_CENTRAUX=Services Centraux
SERVICES_DECONCENTRES=Services déconcentrés
ORGANISMES_SOUS_TUTELLE=Organismes sous tutelle
ORGANES_TERRITORIAUX=Organes territoriaux
AUTRE_SERVICES_SOUS_TUTELLE=Autre organismes sous tutelle

#static content
footer.text=Rapport sur les priorités et la planification \n Ministère ${portefeuille}
default.total=Total
#section 1 specific styles
#cartographie
section1.cartographie.table.style=TextBasedTableBase
#fiche portefeuille table styles
section1.ficheportefeuille.table.styles.1.cell=TableCell
section1.ficheportefeuille.table.styles.2=NumberBasedTableBase2
section1.ficheportefeuille.table.styles.2.cell=TableCell

#section 1 static content
section1.ausujetprotefeuille.title.text=Au sujet du portefeuille
#le ministere
section1.leministere.title.text=Le ministère
section1.leministere.organigramme.title.text=Organigramme du ministère
#la mission
section1.lamission.title.text=La mission
section1.cartographie.title.text=La cartographie des programmes du portefeuille :
section1.cartographie.table.headers.1=Structure de programme
section1.cartographie.table.headers.2=Structure organisationnelle

#fiche portefeuille
section1.ficheportefeuille.title.text=Fiche Portefeuille (voir tableau ci-après)
section1.ficheportefeuille.gestionnaire.text=Gestionnaire responsable : Ministre de ${gestionnaire}

section1.ficheportefeuille.table.1.title=Répartition des crédits de paiements et les autorisations d’engagement par programme (en milliers de dinars) (version B)


section1.ficheportefeuille.demarche.title.text=Démarche adoptée pour le budget programme ${n}:
section1.ficheportefeuille.demarche.text.0=Dans le cadre de la mise en oeuvre de la Loi organique n°18-15 du 02 septembre 2018 relative aux lois de finances, la répartition par portefeuille de programme et par programme en autorisations d’engagement et en crédits paiement conformément à l’état « B » du projet de loi de finances pour 2026 présente les crédits respectifs devant faire l’objet des décrets de répartitions par sous-programme et titre.
section1.ficheportefeuille.demarche.text.1=Aussi, au titre de cet exercice budgétaire en mode « LOLF », il est privilégié de poursuivre l’adoption d’une structure de programme adaptée à la structure organisationnelle en vigueur lorsque celle-ci traduit la politique publique sectorielle. Le cas échéant, une réflexion devra être menée pour ce faire.
section1.ficheportefeuille.demarche.text.2=A l’effet de préserver l’exécution des dépenses de personnel (Rémunérations) et les subventions de l’État aux établissements publics à caractère administratif (EPA), les crédits y afférents sont portés à l’indicatif des programmes associés aux services gestionnaires de l’administration générale de l’ensemble des ministères et institutions.
section1.ficheportefeuille.demarche.text.3=Toutefois, dans le présent document portant Rapport sur les Priorités et la Planification, il a été procédé à une répartition prévisionnelle par programme de l’ensemble des crédits (y compris ceux du personnel) à l’effet d’évaluer l’effort budgétaire consenti, en direction de chaque programme pour l’atteinte des objectifs fixés, tout en précisant que les dépenses communes à l’ensemble des programmes ont fait l’objet de l’application d’une clé de répartition induisant une estimation des crédits « au dinar près ».


section1.ficheportefeuille.table.2.title=Répartition des crédits de paiements et des autorisations d’engagement par programme (en milliers de dinars)

section1.ficheportefeuille.table.3.title=Répartition des crédits des programmes par type de centre de responsabilitées (en dinars)

section1.ficheportefeuille.table.4.title=Répartition des crédits des programmes et titre-année %s (en milliers de dinars)
section1.ficheportefeuille.table.4.header.title=Programme
section1.ficheportefeuille.table.4.total.title=Total des dépenses

section1.ficheportefeuille.table.5.title=Répartition du portefeuille par titre et type de centre de responsabilité année %s (en milliers de dinars)

section1.ficheportefeuille.table.6.title=Évolutions des dépense par programme (en milliers de dinars)
section1.ficheportefeuille.table.6.header.title=Programme
section1.ficheportefeuille.table.6.headers.1=Dépenses réelles année %s
section1.ficheportefeuille.table.6.headers.2=Estimation des dépenses année %s
section1.ficheportefeuille.table.6.headers.3=Dépenses prévues année %s
section1.ficheportefeuille.table.6.headers.4=Dépenses prévues année %s
section1.ficheportefeuille.table.6.headers.5=Dépenses prévues année %s
section1.ficheportefeuille.table.6.total.title=Total des depenses

section1.ficheportefeuille.table.7.title=Évolutions des postes ouverts par type de service
section1.ficheportefeuille.table.7.header.title=Type de services
section1.ficheportefeuille.table.7.headers.1=%s
section1.ficheportefeuille.table.7.headers.2=%s
section1.ficheportefeuille.table.7.headers.3=%s
section1.ficheportefeuille.table.7.headers.4=%s
section1.ficheportefeuille.table.7.headers.5=%s
section1.ficheportefeuille.table.7.total.title=Total des postes

#section 2
section2.planification.title.1.text=Planification détaillée du programme %02d
section2.planification.title.2.text=Présentation du programme
section2.planification.title.3.text=Programme %d: %s
section2.ficheprogramme.title.1.text=Fiche programme :
section2.ficheprogramme.title.2.text=Nom du programme %d: %s
section2.ficheprogramme.title.3.text=Gestionnaire responsable : %s

section2.ficheprogramme.table.1.title=Présentation des objectifs et des indicateurs de performance du programme


section2.ficheprogramme.table.3.title=Dépenses du sous-programme %s par titre et type de centre de responsabilité année %s (en milliers de dinars)

section2.ficheprogramme.table.4.title=Dépenses du programme %s par sous-programme année %s (en milliers de dinars)
section2.ficheprogramme.table.4.header.title=Sous-programme

section2.ficheprogramme.table.5.title=Évolution des dépenses par sous-programme (en milliers de dinars)
section2.ficheprogramme.table.5.header.title=Sous-programme
section2.ficheprogramme.table.5.headers.1=Dépenses réelles année %s
section2.ficheprogramme.table.5.headers.2=Estimations des dépenses année %s
section2.ficheprogramme.table.5.headers.3=CP prévus année %s
section2.ficheprogramme.table.5.headers.4=CP prévus année %s
section2.ficheprogramme.table.5.headers.5=CP prévus année %s
section2.ficheprogramme.table.5.total.title=Total

etat.complementaire.title=États complémentaires
etat.complementaire.evolution.postes.salariale.table.title=Prévisions de l’évolution des postes ouverts et de la masse salariale (en milliers de dinars)

etat.complementaire.evolution.depenses.pricipaux.ost.title=Dépenses des principaux organismes sous tutelle (en milliers de dinars)
etat.complementaire.evolution.depenses.pricipaux.ost.header.title=Principaux organismes sous tutelle
etat.complementaire.evolution.depenses.pricipaux.ost.headers.1=Dépenses réelles année %s
etat.complementaire.evolution.depenses.pricipaux.ost.headers.2=Estimation des dépenses année %s
etat.complementaire.evolution.depenses.pricipaux.ost.headers.3=CP prévues année %s
etat.complementaire.evolution.depenses.pricipaux.ost.headers.4=CP prévues année %s
etat.complementaire.evolution.depenses.pricipaux.ost.headers.5=CP prévues année %s
etat.complementaire.evolution.depenses.pricipaux.ost.total.title=Total

etat.complementaire.evolution.depenses.type.ost.title=Dépenses par type d'organisme sous tutelle (en milliers de dinars)
etat.complementaire.evolution.depenses.type.ost.header.title=Organisme sous tutelle par Type
etat.complementaire.evolution.depenses.type.ost.headers.1=Dépenses réelles année %s
etat.complementaire.evolution.depenses.type.ost.headers.2=Estimation des dépenses année %s
etat.complementaire.evolution.depenses.type.ost.headers.3=CP prévues année %s
etat.complementaire.evolution.depenses.type.ost.headers.4=CP prévues année %s
etat.complementaire.evolution.depenses.type.ost.headers.5=CP prévues année %s
etat.complementaire.evolution.depenses.type.ost.total.title=Total

etat.complementaire.evolution.depenses.territoire.title=Prévisions de l’évolution des dépenses par territoire (en milliers de dinars)
etat.complementaire.evolution.depenses.territoire.header.title=Territoire
etat.complementaire.evolution.depenses.territoire.headers.1=Dépenses réelles année %s
etat.complementaire.evolution.depenses.territoire.headers.2=Estimation des dépenses année %s
etat.complementaire.evolution.depenses.territoire.headers.3=CP prévues année %s
etat.complementaire.evolution.depenses.territoire.headers.4=CP prévues année %s
etat.complementaire.evolution.depenses.territoire.headers.5=CP prévues année %s
etat.complementaire.evolution.depenses.territoire.total.title=Total des dépenses
etat.complementaire.evolution.depenses.source.financement.title=Prévisions de l’évolution des dépenses par source de financement (en milliers de dinars)
etat.complementaire.evolution.depenses.source.financement.header.title=Type de source de financement
etat.complementaire.evolution.depenses.source.financement.headers.1=Dépenses réelles année %s
etat.complementaire.evolution.depenses.source.financement.headers.2=Estimation des dépenses année %s
etat.complementaire.evolution.depenses.source.financement.headers.3=CP prévues année %s
etat.complementaire.evolution.depenses.source.financement.headers.4=CP prévues année %s
etat.complementaire.evolution.depenses.source.financement.headers.5=CP prévues année %s
etat.complementaire.evolution.depenses.source.financement.total.title=Total
